[package]
name = "castform"
version = "0.1.0"
authors = ["Zeyi Fan <fanzeyi1994@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = "*"
clap = "*"
failure = "0.1.1"
futures = "0.1.23"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
